### ISSUE TITLE
numpy版本不对应

### ISSUE THREAD

**Issue by cjcjcj666** [FengyuGuo/SphereSfm_MVS_converter#3]
C:\Users\cj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\omnicv\omnicv.py:292: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  mask = np.zeros((h, w // 4), np.bool)
Traceback (most recent call last):
  File "C:\Users\cj\OneDrive\Desktop\input\SphereSfm_MVS_converter\convert_pts.py", line 101, in <module>
    equirect_cam = mapper.cubemap2equirect(cubemap_idx, (equirect_height, equirect_width))
  File "C:\Users\cj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\omnicv\omnicv.py", line 292, in cubemap2equirect
    mask = np.zeros((h, w // 4), np.bool)
  File "C:\Users\cj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\__init__.py", line 353, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by FengyuGuo** [comment]
使用的哪个版本的numpy? 1.20吗？

**Comment by FengyuGuo** [comment]
在我计算机上

numpy                         1.23.4
numpy-quaternion              2022.4.2
omnicv                        1.1.3

这个版本没有复现这个问题，似乎是omnicv中使用了旧的api，有更详细版本信息吗？
